### ISSUE TITLE
.m文件是乱码

### ISSUE THREAD

**Issue by EverettSy** [hhhizzz/languageUnderstanding#1]
请问你项目中的.m文件的作用是什么，我打开是乱码，想请教你这个问题

**Comment by hhhizzz** [comment]
我不记得有.m文件啊 在哪个路径下面？

**Comment by EverettSy** [comment]
main目录下resource

**Comment by hhhizzz** [comment]
不好意思 太久没看过了那个里面是解析时间信息的正则,通过GZIPInputStream压缩过的，所以不能直接用文本编辑器打开，具体可以参考这个项目https://github.com/shinyke/Time-NLP 这个项目
