### ISSUE TITLE
能否提供一些原始测试数据？

### ISSUE THREAD

**Issue by zxsimple** [hhhizzz/languageUnderstanding#2]
能否提供一些诸如“预订一个下周一上午8点到12点之间从北京首都国际机场到上海虹桥机场的头等舱或商务舱航班，要南方航空的，价格8折以内,两千到三千元”的原始数据？

**Comment by hhhizzz** [comment]
你说机票信息之类的数据？根目录的压缩文件就是https://github.com/hhhizzz/languageUnderstanding/blob/master/dump.sql.zip

**Comment by zxsimple** [comment]
@hhhizzz 我导入了dump，发现都是结构化的数据。我是想做一些NLU的尝试，从原始数据中抽取用户的意图和任务属性。如果能提供一些定机票和火车票的原始对话数据就太好了。

**Comment by hhhizzz** [comment]
@zxsimple 这个是没有的 因为这只是个简单的基于规则的项目 并没有使用机器学习的方法

**Comment by zxsimple** [comment]
@hhhizzz 好的，thanks all the same
